# Generated by Django 5.1 on 2024-08-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_message_audio_message_image_message_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picure',
            new_name='picture',
        ),
    ]
