# Generated by Django 5.1 on 2024-08-19 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_rename_picure_userprofile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together={('user1', 'user2')},
        ),
    ]
